### ISSUE TITLE
The --seed parameter is not fixed, which leads to the result of reproduction worse than that in the paper.

### ISSUE THREAD

**Issue by WhuEven** [huawei-noah/multi_hyp_cc#10]
I followed the instructions to reproduce the experiment. But my results are worse than those given in the paper. Is it because the random seed is not fixed? If so, what is the random seed number of the experiment that obtained the results in the paper?

**Comment by smcdonagh** [comment]
Apologies for the delayed reply.

This may be due to random seed. Unfortunately, we do not have record of the random seed used for the paper result. If we find time to rerun the experiments we will note the random seed and update the results accordingly.
