### ISSUE TITLE
How to download the shi_gehler datasets  and cube+ datasets?

### ISSUE THREAD

**Issue by ToChangeBetter** [huawei-noah/multi_hyp_cc#18]
I think your paper is very good ,but i can't download shi_gehler datasets and cube+ datasets. (https://www.isispa.org/illumination-estimation-challenge/data and https://www2.cs.sfu.ca/~colour/data/shi_gehler/) isn't available.I hope to get your reply.Thanks,best!

**Comment by dhernandez0** [comment]
Hi @BichengYang
Sorry for the delay, it seems Shi Gehler is available for download again. Regarding the challenge data, please ask the authors to provide a way to download it.
