### ISSUE TITLE
Is it possible to share the pretrained files

### ISSUE THREAD

**Issue by dandanji-2020** [huawei-noah/multi_hyp_cc#3]

**Comment by xuhui1994** [comment]
我下载好了这个预训练文件了，你要吗？留邮箱

**Comment by dhernandez0** [comment]
Sorry, we can't provide that. However, you can run our experiment bash scripts to train the models.

**Comment by xuhui1994** [comment]
> Sorry, we can't provide that. However, you can run our experiment bash scripts to train the models.

I just want know the pretrained files name is vgg11-bbd30ac9.pth or else?

**Comment by dhernandez0** [comment]
Sorry, not sure what filename it was, we used pytorch 1.4 and torchvision 0.5. And the pre-trained weights should be automatically downloaded.
