### ISSUE TITLE
How to use datasets?

### ISSUE THREAD

**Issue by xuhui1994** [huawei-noah/multi_hyp_cc#4]
I have download Shi_gehler、Nus、Cube three datasets. Now I dont know how to use these datasets.  Is it just a matter of putting the data sets in the right path?Or preprocess the data.

**Comment by dhernandez0** [comment]
You need to set "data/paths.json" to your dataset path.

**Comment by dhernandez0** [comment]
See this answer: https://github.com/huawei-noah/multi_hyp_cc/issues/5#issuecomment-667210655

**Comment by xuhui1994** [comment]
Thank you for your reply. I run the experiment8.sh which includes 3 .py file. The first two file (hold_out.py   crossvalidation.py   )has been run sucessfully. And the last file inference_datasets.py is not sucessfully. The exception is below, I debug it but it doesnt works! So I need your help.The datasets file is yours. I think the module apply_gamma_correction in utils.py is in bottom,












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/multi_hyp_cc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 凌晨0:26
收件人:&nbsp;"huawei-noah/multi_hyp_cc"<multi_hyp_cc@noreply.github.com&gt;;
抄送:&nbsp;"威爵"<978188311@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huawei-noah/multi_hyp_cc] How to use datasets? (#4)





 
See this answer: #5 (comment)

**Comment by xuhui1994** [comment]
Hi！Whether I run inference.py or inference_datasets.py. It occours a error in core/ultis.py!&nbsp;The reason is that illum is None, so the value of IM is NAN, which leads to the final error.But I dont konw why the value of illum is none.I am in urgent need of your help !







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/multi_hyp_cc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月1日(星期六) 凌晨0:26
收件人:&nbsp;"huawei-noah/multi_hyp_cc"<multi_hyp_cc@noreply.github.com&gt;;
抄送:&nbsp;"威爵"<978188311@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huawei-noah/multi_hyp_cc] How to use datasets? (#4)





 
See this answer: #5 (comment)

**Comment by xuhui1994** [comment]
Hi !&nbsp;I am very interested in your project, you made some changes to the code a few days ago, and now I can run all the code successfully.Thank you very much.I have now tested my own images, which are PNG images that I downloaded from the network and can be directly visualized .And these images have no gt.txt information. When I used inference.py to &nbsp;test these images. The code could run successfully, but the images generated were all black. Can you help me with this problem?Looking forward to hearing from you!&nbsp;The green image below is the input image and the black image is the output.







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huawei-noah/multi_hyp_cc"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 晚上10:37
收件人:&nbsp;"huawei-noah/multi_hyp_cc"<multi_hyp_cc@noreply.github.com&gt;;
抄送:&nbsp;"威爵"<978188311@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huawei-noah/multi_hyp_cc] How to use datasets? (#4)





 
You need to set "data/paths.json" to your dataset path.
