### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by xuhui1994** [huawei-noah/multi_hyp_cc#5]
when I run bash ./experiment/experiment3.sh.  It occurs "FileNotFoundError: [Errno 2] No such file or directory: 'data/nus/cv_metadata.mat'". I download nus png file.I cant find where mat is . Anyone can help me solve it.

**Comment by dhernandez0** [comment]
Unfortunately, we are reading the dataset in an internal format. When I have some time I'll create an script to pre-process the dataset. I'll let you know when that's ready here. Thanks for letting us know this issue!

**Comment by xuhui1994** [comment]
I have run the the experient3.sh that the dataset is nus，I am confused about the output image size is 64x64. I want to know why setting the small size? It is just to save the memory? And can I set the size bigger,for example,128x128 or 256x256?

**Comment by dhernandez0** [comment]
Hi @xuhui1994 

First, I've made some changes to make the preprocessing the datasets easier. Please, check cc_data folder, each dataset has a script, just download the corresponding dataset (zip files, etc) in the corresponding folder and run the script, it will prepare the data for the code.

Regarding image resolution, we use 64x64 for saving memory and processing time. We did some initial experiments with bigger resolutions and we saw small improvement. But you're welcome to try that, just keep in mind you will have to reduce your batch size or change the code to use multi-gpu training (for the extra memory).

I hope that helps, let me know if you need more help.
