### ISSUE TITLE
where to set multiple-gpu training mode?

### ISSUE THREAD

**Issue by TengFeiHan0** [huawei-noah/multi_hyp_cc#7]
I'd like to train your network using 8 gpus, however, I didn't find where can I change. any cues would be highly appreciated.

**Comment by dhernandez0** [comment]
Hi! The code does not support multi-gpu training, it should not be difficult to implement but you would have to do it yourself. See https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html
