### ISSUE TITLE
how to run the code to get experiments result of table 5 in the paper

### ISSUE THREAD

**Issue by EmilySmile** [huawei-noah/multi_hyp_cc#8]
how to run the code to get experiments result of table 5 in the paper,
i dont't find .sh to do this

**Comment by dhernandez0** [comment]
Thanks for reporting this, this is fixed now. The readme has been fixed referencing the right script (experiment12.sh). Note that "Ours" in Table 5 is also row 5 (# candidates=120) of Table 8 in arxiv version, so experiment13.sh should also generate the same results.
