### ISSUE TITLE
The data in datasets\ccm\canon_eos_550d.txt is wrong

### ISSUE THREAD

**Issue by EmilySmile** [huawei-noah/multi_hyp_cc#9]
The data in datasets\ccm\canon_eos_550d.txt is wrong, since the  accumulation in each row is not equal to 1.

4.65227786 -1.22267496  0.22805598
0.33818136  1.2896247  -0.51538961
-0.59128451 -0.34427786  1.89780144

can you produce right color correction matrix

**Comment by dhernandez0** [comment]
Thanks for reporting this, this is fixed now. I have copied the CCM from dcraw project (https://github.com/6by9/dcraw/blob/master/dcraw.c)
